# NUMPY

In [1]:
import numpy as np
import pandas as pd

In [3]:
a= np.array([[1,2,3],[2,4,5],[4,5,6]],dtype=np.complex, ndmin=0,)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [2.+0.j 4.+0.j 5.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [4]:
idtype= np.dtype([('Name', 'S20'), ('Age', 'i1'), ('Marks', 'f4')])
s=np.array([('Sagar', 24 , 50), ('Mayuri', 21 , 45)], dtype=idtype)
print(s)

[(b'Sagar', 24, 50.) (b'Mayuri', 21, 45.)]


In [5]:
a= np.array([[1,2,3],[4,2,5]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [2 5]]


In [6]:
a= np.array([[1,2,3],[4,8,8]])
b= a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [8 8]]


In [7]:
x=np.ones((5,4),dtype=int)
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
x=np.arange(30)
y=slice(3,30,5)

print(x[y])

In [8]:
x=np.arange(30)
y=x[3:30:5]                   #(start, stop, end)

print(y)

[ 3  8 13 18 23 28]


In [9]:
a=np.arange(20)
print(a[5:])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('\t')
print("Slice 1st row")
print(a[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
	
Slice 1st row
[[4 5 6]
 [7 8 9]]


In [11]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print('our array is :')
print(a)
print('\t')

print(a[...,1])
print('\t')

print(a[1,...])
print('\t')

print(a[...,1:])

our array is :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
	
[2 5 8]
	
[4 5 6]
	
[[2 3]
 [5 6]
 [8 9]]


In [12]:
x= np.array([[1,2],[3,4],[5,6]])
y= x[[0,1,2],[1,0,1]]             #(0,1)(1,0)(2,1)
print(y)

[2 3 6]


In [13]:
x= np.array([[1,2,3],[4,5,6],[6,7,8],[7,2,9]])
print('Our original Array is :')
print(x)
print('\t')

rows=np.array([[0,0],[3,3]])
cols=np.array([[0,2],[0,2]])
y=x[rows,cols]  #(0,0)(0,2)(3,0)(3,2) [compare with r &c] #this step is imp bcz we have to merge rows and cols with input(x)
print('the corner elements :')
print(y)

Our original Array is :
[[1 2 3]
 [4 5 6]
 [6 7 8]
 [7 2 9]]
	
the corner elements :
[[1 3]
 [7 9]]


In [14]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is:')
print(x)
print('\n')

# slicing
z = x[1:4,1:3]  #[row,col]
print('After slicing, our array becomes:')
print(z)
print('\n')
# using advanced index for column 
y = x[1:4,[1,2]]
print('Slicing using advanced index for column') 
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column
[[ 4  5]
 [ 7  8]
 [10 11]]


In [ ]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print('Our array is:')
print(x)
print('\n')

# Now we will print the items greater than 5 print 'The items greater than 5 are:
print('Number greater than 5')
print (x[x>5])

# PANDAS

In [15]:
a= np.array(['s','a','g','a','r'])
b= pd.Series(a)
print(b)

0    s
1    a
2    g
3    a
4    r
dtype: object


In [16]:
a={'a': 2, 'b':3, 'c':4, 'd':5, 'e':6}
b= pd.Series(a, index= ['s','a','g','a','r'])
print(b)

s    NaN
a    2.0
g    NaN
a    2.0
r    NaN
dtype: float64


In [17]:
s=pd.Series([1,2,3,4,5], index= ['s','a','g','a','r'])
print(s[:3])

s    1
a    2
g    3
dtype: int64


In [18]:
s=pd.Series([1,2,3,4,5], index= ['s','a','g','a','r'])
print(s[-3:])

g    3
a    4
r    5
dtype: int64


In [19]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
#retrieve a single element
print (s['a'])

1


In [20]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
#retrieve multiple elements
print (s[['a','c','e']])

a    1
c    3
e    5
dtype: int64


In [ ]:
####DataFrame#####

In [21]:
data= [1,2,3,4,5,6]
s= pd.DataFrame(data)
print(s)

   0
0  1
1  2
2  3
3  4
4  5
5  6


In [22]:
data= [1,2,3,4,5,6]
s= pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [23]:
data= [['Sagar', 24, 'Amt'],['Mayuri', 20, 'Amt'], ['Tejas',21, 'Nag']]
s= pd.DataFrame(data,columns=['Name','Age','City'],dtype=float)    #columns   [s is imp]
print(s)

     Name   Age City
0   Sagar  24.0  Amt
1  Mayuri  20.0  Amt
2   Tejas  21.0  Nag


In [24]:
data={'Name':['Sagar','Mayuri','Vishal'], 'Age':[20,13,5], 'City':['Amt', 'Nagpur', 'Amt']} #{}braket is imp
s= pd.DataFrame(data)
print(s)

     Name  Age    City
0   Sagar   20     Amt
1  Mayuri   13  Nagpur
2  Vishal    5     Amt


In [25]:
data={'Name':['Sagar','Mayuri','Vishal'], 'Age':[20,13,5], 'City':['Amt', 'Nagpur', 'Amt']}
s= pd.DataFrame(data, index=['Rank1','Rank2','Rank3'])
print(s)

         Name  Age    City
Rank1   Sagar   20     Amt
Rank2  Mayuri   13  Nagpur
Rank3  Vishal    5     Amt


In [26]:
a=[{'a':1,'b':2},{'a':3, 'b':4, 'c':5}]  #a=1,3 b=2,4 c=NaN,5
b= pd.DataFrame(a,index=['First', 'Second'])
print(b)

        a  b    c
First   1  2  NaN
Second  3  4  5.0


In [27]:
a=[{'Name': 'Sagar',},{'Marks': 20},{'Subject': 'Maths'}]
b= pd.DataFrame(a)
print(b)

    Name  Marks Subject
0  Sagar    NaN     NaN
1    NaN   20.0     NaN
2    NaN    NaN   Maths


In [28]:
a={'Name':['Sagar','Mayuri','Shraddha', 'Yoyo'], 'Age':[24,20,25,23], 'Subjects':['Maths','Science', 'English', 'Physics'], 'Marks':[80,89,95,98]}
b=pd.DataFrame(a,index=['Serial 1', 'Serial 2', 'Serial 3', 'Serial4'])
print(b)

              Name  Age Subjects  Marks
Serial 1     Sagar   24    Maths     80
Serial 2    Mayuri   20  Science     89
Serial 3  Shraddha   25  English     95
Serial4       Yoyo   23  Physics     98


In [ ]:
a= {'one': pd.Series([1,2,3], index=['a','b','c']), 'two': pd.Series([1,2,3,4], index=['y','a','s','h'])}
b=pd.DataFrame(a)
print(b)
print('\t')
#Adding new column

print('Adding new column :')
b['three']= pd.Series([10,20,30,40], index=['a','b','c','d'])
print(b)
print('\t')

#Adding new column with existing column
print('Adding new column 2:')
b['four']=b['one']+ b['three']
print(b)
print('\n')

# using del function
print ("Deletingthe first column using DEL function:")
del b['one']
print (b)
print('\t')

# using pop function
print ("Deletinganother column using POP function:")
b.pop('two')
print (b)

In [6]:
a= {'one': pd.Series([1,8,3], index=['a','b','c']), 'two': pd.Series([1,2,3,4], index=['y','a','s','h'])}
b= pd.DataFrame(a)
print(b.loc['a'])


one    1.0
two    2.0
Name: a, dtype: float64


In [14]:
a= {'one': pd.Series([1,8,3], index=['a','b','c']), 'two': pd.Series([1,2,3,4], index=['a','b','c','d'])} #index=() values same*
c= pd.DataFrame(a)
print(c.iloc[1])


one    8.0
two    2.0
Name: b, dtype: float64


In [13]:
d = {'one' : pd.Series([1,6,3], index=['a','b','c']), 'two' : pd.Series([1,5,3,4], index=['a','b','c','d'])}
df = pd.DataFrame(d)
print (df.iloc[1])          #indexing(0,1,2)

one    6.0
two    5.0
Name: b, dtype: float64


In [17]:
a= pd.DataFrame([[1,2],[3,4]], columns=['a','b'])
b= pd.DataFrame([[5,6],[7,8]], columns=['a','b'])
print(a)
print(b)
print('\t')
print('merge')
c=a.append(b)
print(c)

   a  b
0  1  2
1  3  4
   a  b
0  5  6
1  7  8
	
merge
   a  b
0  1  2
1  3  4
0  5  6
1  7  8


In [28]:
s= pd.Series(np.random.randn(5))
print(s)
print('\t')

print('The axes are :')
print(s.axes)
print('\t')

print('Is it empty')
print(s.empty)
print('\t')

print('The dimension is :', s.ndim)
print('\t')

print('Size of object :', s.size)
print('\t')

print('The actual data series is :')
print(s.values)

print ("The first two rows of the data series:")
print (s.head(2))
print('\t')

print ("The last two rows of the data series:")
print (s.tail(2))
print('\t')

0   -1.368307
1    0.049143
2    1.105786
3   -1.471672
4   -0.436449
dtype: float64
	
The axes are :
[RangeIndex(start=0, stop=5, step=1)]
	
Is it empty
False
	
The dimension is : 1
	
Size of object : 5
	
The actual data series is :
[-1.36830725  0.04914293  1.10578578 -1.47167229 -0.43644917]
The first two rows of the data series:
0   -1.368307
1    0.049143
dtype: float64
The last two rows of the data series:
3   -1.471672
4   -0.436449
dtype: float64


In [8]:
#creating dictionary for SERIES
a = {'Name':pd.Series(['Sagar', 'Rajat', 'Aniket', 'Vaishnav', 'Kapil']), 'Age':pd.Series([24,27,24,25,29]), 
     'Rating':pd.Series([9.9,5.5,4.8,9.4,5.6]), 'Location':pd.Series(['Amravati','Arjun', 'Pune','Nagpur','Pakistan'])}

#Creating Dataframe
df=pd.DataFrame(a)
print('OUR DATA IS HERE : ')
print(df)
print('\t')

print ("The transpose of the data series is:")
print (df.T)
print('\t')

print ("Row axis labels and column axis labels are:")
print (df.axes)

#repeat as mentioned above.

OUR DATA IS HERE : 
       Name  Age  Rating  Location
0     Sagar   24     9.9  Amravati
1     Rajat   27     5.5     Arjun
2    Aniket   24     4.8      Pune
3  Vaishnav   25     9.4    Nagpur
4     Kapil   29     5.6  Pakistan
	
The transpose of the data series is:
                 0      1       2         3         4
Name         Sagar  Rajat  Aniket  Vaishnav     Kapil
Age             24     27      24        25        29
Rating         9.9    5.5     4.8       9.4       5.6
Location  Amravati  Arjun    Pune    Nagpur  Pakistan
	
Row axis labels and column axis labels are:
[RangeIndex(start=0, stop=5, step=1), Index(['Name', 'Age', 'Rating', 'Location'], dtype='object')]


In [15]:
a = {'Name':pd.Series(['Sagar', 'Rajat', 'Aniket', 'Vaishnav', 'Kapil']), 'Age':pd.Series([24,27,24,25,29]), 
     'Rating':pd.Series([9.9,5.5,4.8,9.4,5.6]), 'Location':pd.Series(['Amravati','Arjun', 'Pune','Nagpur','Pakistan'])}

#Creating Dataframe
df=pd.DataFrame(a)
print('OUR DATA IS HERE : ')
print(df)
print('\t')

print (df.sum())               #it will add all row (axis=0) 
print('\t')

print (df.sum(1))              #it will add Age+Rating 
print('\t')

print('Mean of DataFrame')
print (df.mean())
print('\t')

print('standard deviation of numerical column')
print (df.std())
print('\t')

print (df.describe())
print('\t')

print (df.describe(include=['object']))
print('\t')

print (df. describe(include='all'))

OUR DATA IS HERE : 
       Name  Age  Rating  Location
0     Sagar   24     9.9  Amravati
1     Rajat   27     5.5     Arjun
2    Aniket   24     4.8      Pune
3  Vaishnav   25     9.4    Nagpur
4     Kapil   29     5.6  Pakistan
	
Name          SagarRajatAniketVaishnavKapil
Age                                     129
Rating                                 35.2
Location    AmravatiArjunPuneNagpurPakistan
dtype: object
	
0    33.9
1    32.5
2    28.8
3    34.4
4    34.6
dtype: float64
	
Mean of DataFrame
Age       25.80
Rating     7.04
dtype: float64
	
standard deviation of numerical column
Age       2.167948
Rating    2.408942
dtype: float64
	
             Age    Rating
count   5.000000  5.000000
mean   25.800000  7.040000
std     2.167948  2.408942
min    24.000000  4.800000
25%    24.000000  5.500000
50%    25.000000  5.600000
75%    27.000000  9.400000
max    29.000000  9.900000
	
         Name  Location
count       5         5
unique      5         5
top     Kapil  Amravati
freq   

In [25]:
def sagar(x,y):
    return x+y
df=pd.DataFrame(np.random.randn(5,3), columns=['c1','c2','c3'])  #randn(5,3) give 5rows and 3 columns
a=df.pipe(sagar,2)  #(function,parameter)assing the function and the appropriate number of parameters as pipe arguments.
print(a)
print('\t')

a=df.apply(np.mean)
print (a)
print('\t')

a=df.apply(np.mean,axis=1)
print (a)
print('\t')

a=df.apply(lambda x: x.max() - x.min())
print (a)
print('\t')

a=df.applymap(lambda x:x*100)
print(a)
print('\t')

         c1        c2        c3
0  3.551632  2.682398  2.872540
1  2.038109  1.278622  1.054977
2  0.856306  0.982943  2.282238
3  3.747750  2.442255  1.965066
4  0.894355  2.699391  2.042753
	
c1    0.217630
c2    0.017122
c3    0.043515
dtype: float64
	
0    1.035523
1   -0.542764
2   -0.626171
3    0.718357
4   -0.121167
dtype: float64
	
c1    2.891443
c2    1.716448
c3    1.817564
dtype: float64
	
           c1          c2         c3
0  155.163152   68.239811  87.254042
1    3.810877  -72.137785 -94.502335
2 -114.369366 -101.705705  28.223839
3  174.774973   44.225475  -3.493387
4 -110.564461   69.939092   4.275343
	


In [28]:
a= pd.DataFrame(np.random.randn(10,3), columns=['a','b','c'])
b= pd.DataFrame(np.random.randn(4,3), columns=['a','b','c'])     #it gives 4 rows and 3 columns
df=a.reindex_like(b)
print(df)

          a         b         c
0  0.442441 -0.086740 -1.763269
1 -0.430243  1.832548  1.114925
2  0.841238 -0.218636 -0.215747
3 -0.209066  0.896536  2.433826


In [30]:
df1=pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df2=pd.DataFrame(np.random.randn(2,3),columns=['col1','col2','col3'])
print(df2.reindex_like(df1))
print('\t')

print('Data Frame with forward fill')
print(df2.reindex_like(df1, method='ffill'))
print('\t')

print ("Data Frame with Forward Fill limiting to 1:")
print (df2.reindex_like(df1,method='ffill',limit=1))

       col1      col2      col3
0 -0.450933 -0.372429  0.843557
1 -0.690397 -0.563992  0.168681
2       NaN       NaN       NaN
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN
	
Data Frame with forward fill
       col1      col2      col3
0 -0.450933 -0.372429  0.843557
1 -0.690397 -0.563992  0.168681
2 -0.690397 -0.563992  0.168681
3 -0.690397 -0.563992  0.168681
4 -0.690397 -0.563992  0.168681
5 -0.690397 -0.563992  0.168681
	
Data Frame with Forward Fill limiting to 1:
       col1      col2      col3
0 -0.450933 -0.372429  0.843557
1 -0.690397 -0.563992  0.168681
2 -0.690397 -0.563992  0.168681
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN


In [31]:
df1=pd.DataFrame(np.random.randn(6,3), columns=['c1','c2','c3'])
print(df1)
print('After renaming row and columns')
print(df1.rename(columns={'c1':'col1', 'c2':'col2'}, index={0:'Sagar', 1:'Mulchand', 2:'Bhamburkar'}))

         c1        c2        c3
0 -1.316958 -0.505094  0.145460
1  1.490915  1.070622 -0.028969
2  0.207632 -0.234829 -0.330135
3  0.845519  0.489536 -0.614570
4  0.034487  0.582408 -0.539299
5  0.184485  0.170348  0.590394
After renaming row and columns
                col1      col2        c3
Sagar      -1.316958 -0.505094  0.145460
Mulchand    1.490915  1.070622 -0.028969
Bhamburkar  0.207632 -0.234829 -0.330135
3           0.845519  0.489536 -0.614570
4           0.034487  0.582408 -0.539299
5           0.184485  0.170348  0.590394
